### PR TITLE
BACKLOG-39530 Cron recurrence null issue

### PR DESCRIPTION
**Pull request by srallapa**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 6m 5s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.web.http.api.resources.SchedulerResourceUtilTest.testHandlePdiScheduling_requestParamsAreTransferred</b> (click to expand)</summary><p>

```
class org.mockito.Matchers tried to access private method 'void org.mockito.internal.progress.ThreadSafeMockingProgress.<init>()' (org.mockito.Matchers and org.mockito.internal.progress.ThreadSafeMockingProgress are in unnamed module of loader 'app')
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.SchedulerResourceUtilTest.testHandlePdiScheduling_notAllRequestParamsAreTransferred</b> (click to expand)</summary><p>

```
Could not initialize class org.mockito.Matchers
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.proxies.BlockStatusProxyTest.testHasValidGettersAndSetters</b> (click to expand)</summary><p>

```
NONE
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.services.SchedulerServiceTest.testCreateJobException</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **183**, Failures: **4**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-77/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by ddiroma** [comment]
@srallapa Please check if the unit test failures are from your code changes. 
Also, please change the copyright date to 2024. Thanks.

**Comment by srallapa** [comment]
> @srallapa Please check if the unit test failures are from your code changes. Also, please change the copyright date to 2024. Thanks.

The junit tests failing are not related to the code changes, they are also failing in the master branch.

**Comment by buildguy** [comment]
### :warning: Build finished in 5m 54s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.web.http.api.resources.SchedulerResourceUtilTest.testHandlePdiScheduling_requestParamsAreTransferred</b> (click to expand)</summary><p>

```
class org.mockito.Matchers tried to access private method 'void org.mockito.internal.progress.ThreadSafeMockingProgress.<init>()' (org.mockito.Matchers and org.mockito.internal.progress.ThreadSafeMockingProgress are in unnamed module of loader 'app')
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.SchedulerResourceUtilTest.testHandlePdiScheduling_notAllRequestParamsAreTransferred</b> (click to expand)</summary><p>

```
Could not initialize class org.mockito.Matchers
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.proxies.BlockStatusProxyTest.testHasValidGettersAndSetters</b> (click to expand)</summary><p>

```
NONE
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.services.SchedulerServiceTest.testCreateJobException</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **183**, Failures: **4**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-77/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :warning: Build finished in 3m 57s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 4 test(s) failed:

<details><summary><b>org.pentaho.platform.web.http.api.resources.SchedulerResourceUtilTest.testHandlePdiScheduling_requestParamsAreTransferred</b> (click to expand)</summary><p>

```
class org.mockito.Matchers tried to access private method 'void org.mockito.internal.progress.ThreadSafeMockingProgress.<init>()' (org.mockito.Matchers and org.mockito.internal.progress.ThreadSafeMockingProgress are in unnamed module of loader 'app')
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.SchedulerResourceUtilTest.testHandlePdiScheduling_notAllRequestParamsAreTransferred</b> (click to expand)</summary><p>

```
Could not initialize class org.mockito.Matchers
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.proxies.BlockStatusProxyTest.testHasValidGettersAndSetters</b> (click to expand)</summary><p>

```
NONE
```

</p></details>

<details><summary><b>org.pentaho.platform.web.http.api.resources.services.SchedulerServiceTest.testCreateJobException</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **183**, Failures: **4**, Skipped: **13** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-77/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
