### PR TITLE
[SP-6650][BISERVER-14374] PUC UI now allows users to set the time zone of a scheduled job to something other than the server's time zone. Job will be scheduled accordingly. -- backport to 10.2 suite for 10.2.0.2

### PR DESCRIPTION
**Pull request by ddiroma**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 2m 9s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 25s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 4s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 9m 12s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl core,ui
```
---
:ok_hand: All tests passed!
 
Tests run: **387**, Failures: **0**, Skipped: **10** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-232/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]

**Pull request merged**
