### PR TITLE
Addresses BACKLOG-39987: fix some schedules table issues

### PR DESCRIPTION
**Pull request by mbrasil**
@pentaho/millenniumfalcon please review

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 8m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **133**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-146/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by Pancho7 — APPROVED** [review]

**Comment by buildguy** [comment]
### :x: Build failed in 45s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 34s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl ui
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by JoaoEnesGoncalves — APPROVED** [review]

**Comment by mbrasil** [comment]
build is failing but the issue is being addressed on a pending change in maven-parent-poms

**Pull request merged**
