### PR TITLE
[BISERVER-15124] Creating a bootstrap lifecycle listener to allow beans with properties to be initialized and execute on runtime

### PR DESCRIPTION
**Pull request by rmansoor**

### CODE REVIEW

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 8m 38s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl assembly,core
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 1 test(s) failed:

<details><summary><b>org.pentaho.platform.scheduler2.SchedulerSpringBootStrapLifecycleListenerTest.testDefault</b> (click to expand)</summary><p>

```
Cannot invoke "java.util.List.iterator()" because "lifecycleListenerList" is null
```

</p></details>

  
Tests run: **259**, Failures: **1**, Skipped: **11** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-206/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 39s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl assembly,core
```
---
:ok_hand: All tests passed!
 
Tests run: **260**, Failures: **0**, Skipped: **11** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-206/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 43m 15s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl assembly,core
```
---
:ok_hand: All tests passed!
 
Tests run: **260**, Failures: **0**, Skipped: **11** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-206/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl assembly,core
```
---
:ok_hand: All tests passed!
 
Tests run: **260**, Failures: **0**, Skipped: **11** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-206/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>



---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl assembly,core
```
---
:ok_hand: All tests passed!
 
Tests run: **262**, Failures: **0**, Skipped: **11** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-206/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by angel-ramoscardona — APPROVED** [review]

**Pull request merged**
