### PR TITLE
feat: getFile method for generic file service [BACKLOG-42892]

### PR DESCRIPTION
**Pull request by dcleao**
- added corresponding endpoint `GET /plugin/scheduler-plugin/api/generic-files/{id}`
- added missing `getFileContentWrapper` overload for a string path
- fixed documentation of `getFileContentWrapper`
- fixed `getFileContentWrapper` not throwing `NotFoundException`
- fixed repository provider returning wrong name and capabilities for subtree root folders on `getTree` (would return those of the repository root)
- fixed repository files proper having a null type property
- changed to using repository web service's own `DateAdapter` class instead of duplicating code to convert dates back to `Date`

Issue: https://hv-eng.atlassian.net/browse/BACKLOG-42892

@pentaho/millenniumfalcon, please review.

To be merged with:
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/289

### CODE REVIEW

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 19s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **362**, Failures: **0**, Skipped: **10** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-229/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 29s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **363**, Failures: **0**, Skipped: **10** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-229/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by loonatic — APPROVED** [review]

**Comment by buildguy** [comment]
[comment]: <> (FrogbotReviewComment)

<div align='center'>

[👍 Frogbot scanned this pull request and did not find any new security issues.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 11m 2s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl api,core
```
---
:ok_hand: All tests passed!
 
Tests run: **363**, Failures: **0**, Skipped: **10** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-229/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by davidmsantos90 — APPROVED** [review]

**Pull request merged**
